"""empty message

Revision ID: 8a4f8ff1d0dc
Revises: fa2d2344103c
Create Date: 2022-11-30 12:50:37.310773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4f8ff1d0dc'
down_revision = 'fa2d2344103c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
